pydev debugger: process 1464 is connecting

<class 'AttributeError'>
<class 'AttributeError'>
<class 'AttributeError'>
<class 'AttributeError'>
<class 'AttributeError'>
<class 'AttributeError'>
<class 'AttributeError'>
<class 'AttributeError'>
<class 'AttributeError'>
<class 'AttributeError'>
<class 'AttributeError'>
<class 'AttributeError'>
<class 'AttributeError'>
<class 'AttributeError'>
<class 'AttributeError'>
<class 'AttributeError'>
<class 'AttributeError'>
усднфмхй сяоеьмн нрпхянбюк 9 хгнапюфемхи
оюсгю б веярэ сяоеьмнцн гюбепьемхъ
